<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5486a6ef-c2ae-4939-893d-517943960c77</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockSentiment.Core\StockSentiment.Core.csproj" />
    <ProjectReference Include="..\StockSentiment.Infrastructure\StockSentiment.Infrastructure.csproj" />
  </ItemGroup>

</Project>
